### ISSUE TITLE
Selective entry export by content type

### ISSUE THREAD

**Issue by a-lehdet** [contentful/contentful-export#105]
It would be great if the user could configure which entries by content type or exported. For example, let's say I had content types called _article_, _category_ and _person_ and I only wanted to export _category_ and _person_ entries with a parameter like `--include-content-types ["category", "person"]`.

**Comment by Khaledgarbaya** [comment]
hey @a-lehdet,
did you check the `--query-entries` option?

**Comment by Khaledgarbaya** [comment]
No worries
