### ISSUE TITLE
`management-host` renamed to `host` in 7.0.0

### ISSUE THREAD

**Issue by DanweDE** [contentful/contentful-export#106]
I was wondering why my code wouldn't work with spaces I've been using with this tool before.

Turns out the `--management-host` parameter got renamed to `--host` in 7.0.0. Same goes for the `managementHost` parameter in the options object when used as a npm package.

I'd suggest to re-introduce `--management-host` (cli) and `managementHost` (node) and keep `host` as an alias in both cases.

**Comment by Khaledgarbaya** [comment]
Sorry @DanweDE about the confusion it was changed in the code we forgot to update the README.
the reason we moved to just `host` is that we only use management in the tool so host would be simpler

**Comment by Khaledgarbaya** [comment]
The README will be fixed in https://github.com/contentful/contentful-export/pull/107

**Comment by axe312ger** [comment]
@DanweDE done :)
