### ISSUE TITLE
Attribute "query-entries" doesn't filter assets

### ISSUE THREAD

**Issue by gaapt** [contentful/contentful-export#117]
When you run the tool with a command using `--query-entries` that does not limit the retrieval of assets and, by effect, there is not a direct and clean to omit them from the response.

More information available [in here](https://www.contentfulcommunity.com/t/copy-content-entry-to-another-space/1166/3).

**Comment by Khaledgarbaya** [comment]
Hey @gaapt,
That's the normal behavior, for now, that's why we have `--query-assets`.
I am not sure if we'll add this anytime soon to the tool but we'll keep this in mind

**Comment by anishtimila** [comment]
@Khaledgarbaya I tried to filter only the content without the assets but it downloads all the assets as well. Is there any update on exporting only the related assets for the contents? Or just to filter out contents only?

```
const contentfulExport = require('contentful-export')

const options = {
  spaceId: '*********',
  environmentId: `'****************',`
  managementToken: '******************',
  queryEntries: [
    'sys.id='
  ],
  queryAssets: [],
  contentOnly: true,
  downloadAssets: false
}
contentfulExport(options)``
```
