### ISSUE TITLE
@contentful/axios@^0.18.0 

### ISSUE THREAD

**Issue by shahabshafiee** [contentful/contentful-export#122]
npm i contentful-cli

shows this error:

npm ERR! code E404                                                                                                                                      
npm ERR! 404 Not Found: @contentful/axios@^0.18.0

**Comment by phoebeschmidt** [comment]
@shahabshafiee our most up to date version of the CLI doesn't rely on @contentful/axios anymore, we just use axios v0.19. 

I'm closing because this is out of date. Please open another issue if you have trouble in the future.
