### ISSUE TITLE
"Cannot find any-observable implementation nor global.Observable." in AWS Lambda

### ISSUE THREAD

**Issue by jesusgollonet** [contentful/contentful-export#132]
Hi, I'm trying to run contenful-export on a lambda function running the node 10 runtime but I get the error 

> Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require(\"any-observable/register\") with your preferred implementation, e.g. require(\"any-observable/register\")('rxjs') on applicationload prior to any require(\"any-observable\").

It seems to come from `listr` and `any-observable` as per e.g: https://github.com/SamVerschueren/listr/issues/91 but I've tried every suggestion in issues to no avail (installing `any-observable`, `zen-observable`, `rxjs`, `rxjs-compat` myself). I'm still trying to figure out what's wrong but thought I'd float it here in case anyone has ran into the issue. 

The package works fine on my local machine (osx running node 10.15.3).

This is the code I'm using 
```javascript
const contentfulExport = require('contentful-export');
const AWS = require('aws-sdk');
const s3 = new AWS.S3();

const options = {
    spaceId: process.env.CONTENTFUL_SPACE_ID,
    managementToken: process.env.CONTENTFUL_TOKEN,
    contentOnly: true,
    saveFile: false,
};

module.exports.handler = async event => {
    try {
        const result = await contentfulExport(options);
        const currentVersion = new Date().getTime();
        const uploadResult = await s3
            .putObject({
                Bucket: process.env.ASSETS_BUCKET,
                Key: `content/${currentVersion}.json`,
                Body: JSON.stringify(result),
                ContentType: 'application/json',
            })
            .promise();
        return {
            statusCode: 200,
            body: JSON.stringify({ uploadResult }),
        };
    } catch (e) {
        console.log('Oh no! Some errors occurred!', e);
        return {
            statusCode: 400,
            body: JSON.stringify({ e }),
        };
    }
};

```

**Comment by jesusgollonet** [comment]
Nevermind. the issue comes from `serverless-plugin-optimize`'s handling of peerDependencies. If I turn optimization off the plugin works without a problem. Closing the issue. Cheers!

**Comment by Oatelaus** [comment]
For others coming across this issue, the above is not a fix - turning off bundling causes poor performance in your lambdas and needlessly inflates code sizes.

The proper fix would be a good dependency chain within this project.

**Comment by ekasprzyk** [comment]
Another fix for those folks who have this issue via esbuild.  Here's an example esbuild config for setting up an AWS lambda using serverless-esbuild:

```
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ["@aws-sdk"],
      // The following line is needed to solve an issue from contentful-export dependency
      external: ["any-observable", "rxjs"],
      target: "node18",
      installExtraArgs: ["--legacy-peer-deps"], // same as above comment
      define: { "require.resolve": undefined },
      platform: "node",
      concurrency: 10,
    },
```

Combine this with an imported line in the lambda root:

`import "any-observable/register/rxjs.js";`

And it should work.  You'll have to add any-observable and rxjs (in this case) to the package.json's dependency array too, but it works.
