### ISSUE TITLE
Adding editor interface data query or separate skip?

### ISSUE THREAD

**Issue by verys-jhuang** [contentful/contentful-export#135]
Currently it looks like the only way to skip editor interface is through the config option `skipContentModel`.  I'm currently working on a tool that needs the content types data but not the interface data.  Would it be possible to add a skip separate from `skipContentModel` to editor interface?

Editor interface currently always grabs all editor interface data from every model.  Would it be possible to add an editor interface query similar to content entries / assets?

**Comment by phoebeschmidt** [comment]
Hi @verys-jhuang there is no way to filter on editor interfaces unfortunately, but I've just opened a PR that allows you to skip exporting them :)
