### ISSUE TITLE
Validating export options

### ISSUE THREAD

**Issue by govertb** [contentful/contentful-export#138]
I recently used the `contentful-export` library to archive and migrate a couple of Contentful Spaces and Environments, which worked great! It surprised me though that the options passed to `contentfulExport()` are not validated. If I pass e.g. `{ ... includeArchive: true }` instead of `{ ... includeArchived: true }` there is no warning that I passed an invalid option, and the export continues without exporting archived entries (the default config). To improve the library, I think validation of the export options (or e.g. TypeScript declarations) would be very valuable to have (to prevent data loss due to a misconfigured export). Please let me know if I should forward this feedback to a different place.

**Comment by phoebeschmidt** [comment]
Hey @govertb,

We unfortunately don't have as much capacity to maintain our open source tools as we used to :( We are currently in discussion about typescript-ifying all projects, which would solve the issue you bring up. 

Besides typescript we have no plans to implement better validation, unfortunately. However, PRs are always welcome!

I'm closing this but feel free to open another one in the future.

**Comment by govertb** [comment]
Cool, thanks for getting back to me. 
> We are currently in discussion about typescript-ifying all projects, which would solve the issue you bring up.

+1 for TypeScript support 👍
