### ISSUE TITLE
Pull Entries For A Given ContentType

### ISSUE THREAD

**Issue by dpatra1** [contentful/contentful-export#139]
Hi,

I have a requirement to pull entries for a given contentType and generate a report based on the status like DRAFT or PUBLISHED.

I have tried _CMA, CDA & CPA_, and I see that every API  has its own drawbacks and also I can not make any combination of API calls to full fill my requirement.

I am using Java API to write the service.
**CMA** : I see there is no way I can pull entries for a given contentType.
**CDA** : It only returns the PUBLISHED version of the entries for a given contentType.
**CPA** : It returns both DRAFT & PUBLISHED version of the entries for a given contentType but I don't see a way to find out whether the entry is DRAFT or PUBLISHED. Because I had one entry which was published and then again I unpublished it, but API is still returning that as published entry. When I say its still returning as published entry, I am checking the updatedAt date and version to decide whether its DRAFT and published.

Can someone help me find out the right approach to full fill my requirement using JAVA API?

Thanks,
Deba

**Comment by phoebeschmidt** [comment]
Hi @dpatra1,

You are mistaken about the CMA-- you can pull entries for a given content type using a query like this:

```
https://api.contentful.com/spaces/{{space_id}}/environments/{{environment_id}}/entries?sys.contentType.sys.id[in]=blogPost
```

or using the cli:

```
contentful space export --space-id <space_id> --management-token <CMA_token_here> --query-entries 'sys.contentType.sys.id[in]=person,blogPost'
```

I definitely empathize-- it's tricky to determine the published state of an entry (especially if it has been published before). Here's some info about how to tell: https://www.contentful.com/developers/docs/tutorials/general/determine-entry-asset-state/

Hope this helps!

Cheers,
Phoebe

**Comment by dpatra1** [comment]
Hi Phoebe,

First of all thanks for the reply !

Regarding CMA pulling entries based on contentType, due you have option using JAVA SDK to setContentType ? Because I can see that is provided in CDA/CPA where you can set the contentType but I don't see that in CMA.

`        return cdaClient.fetch(CDAEntry.class)
                .withContentType(contentType)
                .limit(0)
                .all()
                .total();
`
Also I don't see the pagination option in CMA JAVA sdk as well.

About finding the state of an entry, I have seen that page already. But the problem with that is, bulk APIs does not return those fields(_publishedVersion, publishedAt, firstPublishedAt & publishedCounter_). If you are calling **_entryById_** API then it will return those fields. 

So Its going to be performance hit If I wants to pull 10K entries by making 10K calls. If those fields will be returned as part of the bulk API then it will be easier to find out the state. Otherwise, I have to make a bulk API call and then for every entry I have to make getEntryById call to pull those fields which will help me deciding the state which is really a ugly approach.

Or there is any other way  which may be I am not aware of.

Thanks,
Deba

**Comment by rafalniski** [comment]
@dpatra1 

Pulling entries by type is not supported yet in the CMA Java SDK. Can I see your while snippet for calling `bulk API` and then `entryById API`?

**Comment by dpatra1** [comment]
@rafalniski 

Currently I am using CPA, not coded using CMA yet. I was just evaluating what are the options to find out STATUS of entries if I will use CMA.

I was trying CMA bulk API by contentType, looks like its returning _publishedVersion, publishedAt, firstPublishedAt & publishedCounter_ . Let use the change my code and re-write to make normal HTTP calls instead of using CMA Java SDK.

Thank You !!!

**Comment by rafalniski** [comment]
@dpatra1 Just answering your question about how to pass `contentType` to the CMA SDK, here is the example(src/test/kotlin/com/contentful/java/cma/EntryTests.kt):

`val query = hashMapOf(Pair("skip", "1"), Pair("limit", "2"), Pair("content_type", "foo"))`
`assertTestCallback(client!!.entries().async().fetchAll(
                "spaceid", "environmentId", query, TestCallback()) as TestCallback)`

**Comment by phoebeschmidt** [comment]
This seems to have been cleared up, so I'm closing this issue. Please continue any conversation about the java SDK on the correct repository: https://github.com/contentful/contentful-management.java
