### ISSUE TITLE
Content Model Validation Does Not Work !!!

### ISSUE THREAD

**Issue by dpatra1** [contentful/contentful-export#169]
Hi,

I have a content Model where I have the validation for a particular field called "taxonomy_id" which should be unique. I was in the impression that, If anyone trying to create the entry with taxonomy_id already exist, should throw an error. But thats what it is not happening, I can happily click on any existing entry, and create a duplicate of that existing entry with the same taxonomy_Id.

Also when i tried creating entries using SDK(Java & Python), I see the same problem. I could create multiple entries with one taxonomy_id. 

Is this a bug in CMS or I am missing something here. ?? 

Just to be clear, the validation is active.

![Screen Shot 2020-03-19 at 3 49 49 PM](https://user-images.githubusercontent.com/12764176/77121846-675ad280-69f9-11ea-82bc-70ca598ea23b.png)

Thanks,
Deba

**Comment by matthew-contentful** [comment]
Hello Deba,

Please reach out to support for assistance: https://www.contentful.com/support/

Also be mindful that validations only apply during the publish operation.

Thanks, Matthew
