### ISSUE TITLE
A security vulnerability in minimist package (sub-dependency)

### ISSUE THREAD

**Issue by xingjungoh** [contentful/contentful-export#177]
I get a vulnerability issues regarding Package minimist with version less than 1.2.3.

Root cause is an outdated version of mkdirp that requires an older version of minimist.

Pending the next release to include the fix.

**Comment by taihoe** [comment]
It seems there is a new version of mkdirp which doesn't have minimist.
https://github.com/isaacs/node-mkdirp

**Comment by phoebeschmidt** [comment]
we've finally gotten around to updating our dependabot configs so dependencies should stay up to date now going forward. Please open another issue if you have more problems.
