### ISSUE TITLE
Failed to export 404

### ISSUE THREAD

**Issue by Saf98** [contentful/contentful-export#1869]
yarn run cf-export.
The log seems to have an issue with space_id but this is correct?
I get a 404 result in the logs.

```
{
  "scripts": {
    "cf-export": "contentful space export --config contentful/export-config.json --management-token $CONTENTFUL_ACCESS_TOKEN --space-id $CONTENTFUL_SPACE_ID"
  }
}
```

**Comment by Saf98** [comment]
I have logged in and i am already using my space id but still errors??

`{
  "ts": "2024-09-13T19:04:43.227Z",
  "level": "error",
  "error": {
    "originalError": {
      "name": "NotFound",
      "message": "{\n  \"status\": 404,\n  \"statusText\": \"Not Found\",\n  \"message\": \"The resource could not be found.\",\n  \"details\": {\n    \"type\": \"Space\",\n    \"id\": \"$CONTENTFUL_SPACE_ID\"\n  },\n  \"request\": {\n    \"url\": \"/spaces/$CONTENTFUL_SPACE_ID\",\n    \"headers\": {\n      \"Accept\": \"application/json, text/plain, */*\",\n      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",\n      \"X-Contentful-User-Agent\": \"app contentful.cli/3.3.9; feature space-export; sdk contentful-management.js/11.33.0; platform node.js/v20.0.0; os Windows/v20.0.0;\",\n      \"CF-Sequence\": \"30fa3793-1caa-426b-89c7-9fa80a37d7a4\",\n      \"Authorization\": \"Bearer ...TOKEN\",\n      \"User-Agent\": \"axios/1.7.5\",\n      \"Accept-Encoding\": \"gzip, compress, deflate, br\"\n    },\n    \"method\": \"get\"\n  },\n  \"requestId\": \"d85c0ff0-dedc-4f41-91e4-f61b3f5dc5a0\"\n}"
    },
    "data": {
      "status": 404,
      "statusText": "Not Found",
      "message": "The resource could not be found.",
      "details": {
        "type": "Space",
        "id": "$CONTENTFUL_SPACE_ID"
      },
      "request": {
        "url": "/spaces/$CONTENTFUL_SPACE_ID",
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/vnd.contentful.management.v1+json",
          "X-Contentful-User-Agent": "app contentful.cli/3.3.9; feature space-export; sdk contentful-management.js/11.33.0; platform node.js/v20.0.0; os Windows/v20.0.0;",
          "CF-Sequence": "30fa3793-1caa-426b-89c7-9fa80a37d7a4",
          "Authorization": "Bearer ...TOKEN",
          "User-Agent": "axios/1.7.5",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "method": "get"
      },
      "requestId": "d85c0ff0-dedc-4f41-91e4-f61b3f5dc5a0"
    }
  }
}`

**Comment by mobikats** [comment]
I am getting a similar error from a script I have left running for a couple of years. It started failing last week.

It will become quite a critical problem as I have integrations partially depending on this now. 

I will see if I can investigate further into this package to see where it is getting upset, but I am likely to be slow at doing this :/

**Comment by mobikats** [comment]
For ref:
✗ npm list contentful-export --depth=0
└── contentful-export@7.19.155

**Comment by Saf98** [comment]
i ended up using the contentful typescript app/extentions until this is fixed.

**Comment by mobikats** [comment]
Thanks @Saf98 , I am looking into alternatives now, the 'contentful-management' library looks promising.

**Comment by mobikats** [comment]
Looking at the open issues, some of them haven't had a response in over a year... it doesn't look as though anyone is maintaining this any more? Although it does get automatic releases made when some dependencies update.

This error looks trivial to solve though, the library depends on some resource it can't find and is barfing on that.

**Comment by Saf98** [comment]
@mobikats I am using this app, https://github.com/marcolink/cf-content-types-generator-app

**Comment by mobikats** [comment]
Thanks @Saf98 , I am currently thinking about a script using the [Contentful CLI ](https://github.com/contentful/contentful-cli)library, I just hope it won't have the same bizarre 404 when starting!

Ideally someone from  @Contentful should just resolve this, it looks like they broke it by accident at the time

**Comment by Saf98** [comment]
let me know hows it goes

**Comment by rustyy** [comment]
> I have logged in and i am already using my space id but still errors??
> 
> `{ "ts": "2024-09-13T19:04:43.227Z", "level": "error", "error": { "originalError": { "name": "NotFound", "message": "{\n \"status\": 404,\n \"statusText\": \"Not Found\",\n \"message\": \"The resource could not be found.\",\n \"details\": {\n \"type\": \"Space\",\n \"id\": \"$CONTENTFUL_SPACE_ID\"\n },\n \"request\": {\n \"url\": \"/spaces/$CONTENTFUL_SPACE_ID\",\n \"headers\": {\n \"Accept\": \"application/json, text/plain, */*\",\n \"Content-Type\": \"application/vnd.contentful.management.v1+json\",\n \"X-Contentful-User-Agent\": \"app contentful.cli/3.3.9; feature space-export; sdk contentful-management.js/11.33.0; platform node.js/v20.0.0; os Windows/v20.0.0;\",\n \"CF-Sequence\": \"30fa3793-1caa-426b-89c7-9fa80a37d7a4\",\n \"Authorization\": \"Bearer ...TOKEN\",\n \"User-Agent\": \"axios/1.7.5\",\n \"Accept-Encoding\": \"gzip, compress, deflate, br\"\n },\n \"method\": \"get\"\n },\n \"requestId\": \"d85c0ff0-dedc-4f41-91e4-f61b3f5dc5a0\"\n}" }, "data": { "status": 404, "statusText": "Not Found", "message": "The resource could not be found.", "details": { "type": "Space", "id": "$CONTENTFUL_SPACE_ID" }, "request": { "url": "/spaces/$CONTENTFUL_SPACE_ID", "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/vnd.contentful.management.v1+json", "X-Contentful-User-Agent": "app contentful.cli/3.3.9; feature space-export; sdk contentful-management.js/11.33.0; platform node.js/v20.0.0; os Windows/v20.0.0;", "CF-Sequence": "30fa3793-1caa-426b-89c7-9fa80a37d7a4", "Authorization": "Bearer ...TOKEN", "User-Agent": "axios/1.7.5", "Accept-Encoding": "gzip, compress, deflate, br" }, "method": "get" }, "requestId": "d85c0ff0-dedc-4f41-91e4-f61b3f5dc5a0" } } }`

@Saf98 - out of curiosity: Did you replace your real space-id in this log given or is it the original unchanged output?

**Comment by Saf98** [comment]
@rustyy i believe this "--space-id $CONTENTFUL_SPACE_ID" should have access to my env.local file in next js. I did try hardcoding it and it made no difference.

**Comment by rustyy** [comment]
@Saf98 from the log you posted, I can conclude the following:

1. you are on Windows
2. your variables like $CONTENTFUL_SPACE_ID did not get resolved, otherwise your space-id could be found in the log

First what are those $XYZ variables? These are environment variables that you assume to be set some how.
The notation used by you are UNIX environment variables, so this will not work on Windows unless you are using WSL or gitBash. On native Windows you need to set them in a different way.

Your assumption concerning your env.local is wrong - your variables do not simple get resolved out of nowhere, the env.local is loaded within nextjs by dotenv/dotenvx but not if you just invoke a npm script.
