### ISSUE TITLE
[Solved] errors with mkdirp@^1.0.3

### ISSUE THREAD

**Issue by orta-sanz** [contentful/contentful-export#194]
Hi family! :rocket: 

Today I'm facing some strange errors when exporting content/models from a new project:
```json
[
  {
    "ts": "2020-04-03T08:06:28.470Z",
    "level": "error",
    "error": {
      "stacktrace": [
        "TypeError: invalid options argument",
        "optsArg (/home/alejandro/code-sandbox/node-test/node_modules/mkdirp/lib/opts-arg.js:13:11)",
        "mkdirp (/home/alejandro/code-sandbox/node-test/node_modules/mkdirp/index.js:11:10)",
        "tryCatcher (/home/alejandro/code-sandbox/node-test/node_modules/bluebird/js/release/util.js:16:23)",
        "ret (eval at makeNodePromisifiedEval (/home/alejandro/code-sandbox/node-test/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)",
        "Task.task (/home/alejandro/code-sandbox/node-test/node_modules/contentful-export/dist/index.js:139:18)",
        "Promise.resolve.then.then.skipped (/home/alejandro/code-sandbox/node-test/node_modules/listr/lib/task.js:167:30)"
      ]
    }
  }
]
```

As you can see `mkdirp` is in the spotlight, so I started to compare the version that I use in another project and in this. The project with the error uses `mkdirp@^1.0.3` and the other one (which it's working fine): `mkdirp@^0.5.1`

I updated the version:
![image](https://user-images.githubusercontent.com/3337555/78338522-3f3fa780-7593-11ea-8375-f5d4acfd1b07.png)

And everything worked correctly again
![image](https://user-images.githubusercontent.com/3337555/78338605-5e3e3980-7593-11ea-816d-24e1589031cb.png)

If you want I can do a PR to change the version, maybe not use that one, or investigate what is happening.

Thanks!

**Comment by phoebeschmidt** [comment]
Hey @orta-sanz,

Thanks for bringing this to our attention! As you can see we recently added dependabot and are in the process of updating all dependencies. 

I'm frustrated our tests didn't catch this regression, but very grateful you already figured out the problem! 

If you're inclined, I'd love a little investigation for why the newest mkdirp causes the error. If it's an easy code fix, I'd be pumped to review that! If it's not, then I'd also review a PR pinning mkdirp back down to the older version.

Cheers,
p

**Comment by makinwab** [comment]
[Here's](https://github.com/contentful/contentful-cli/issues/304) a related issue reported in the CLI repo.
