### ISSUE TITLE
Feature Request: Allow passing of a stream

### ISSUE THREAD

**Issue by roylines** [contentful/contentful-export#214]
Hi. Thanks for creating such an awesome utility for backing up contentful. 

I have a feature request: is it possible to have an option for passing in a stream rather than a directory? This would allow, for example, backing up directly into S3 or other writeable areas. 

Happy to contribute if you take pull requests.

**Comment by phoebeschmidt** [comment]
Hi @roylines, we don't currently support streams but we do accept PRs :)

**Comment by marcolink** [comment]
Since there hasn't been any activity, I will close this for now.
