### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by apaatsio** [contentful/contentful-export#22]
Getting error `/usr/bin/env: ‘node --harmony’: No such file or directory` when trying to run on command line. 

When I Google that error message, all results say that the arguments in hashbang just don't work on Linux.

I'm using contentful-export 2.2.0.

```
❯ uname -a
Linux a1 4.8.14-1-MANJARO #1 SMP PREEMPT Sat Dec 10 23:58:26 UTC 2016 x86_64 GNU/Linux
❯ bash --version
GNU bash, version 4.4.5(1)-release (x86_64-unknown-linux-gnu)
❯ node --version
v6.5.0
❯ npm --version
3.10.3
❯ contentful-export --version
/usr/bin/env: ‘node --harmony’: No such file or directory
```

**Comment by Khaledgarbaya** [comment]
@apaatsio thanks for the report I guess I will remove the `--harmony` for now.
A fix will be landed soon

**Comment by Khaledgarbaya** [comment]
@apaatsio 
please give it few minutes until the ci finishes and a new version should be out in npm.
Sorry again thought `--harmony` will keep the tool backward compatible but meh..
Best,
Khaled

**Comment by apaatsio** [comment]
Thanks for the quick fix!
