### ISSUE TITLE
Error in using contentful-export in Node handler

### ISSUE THREAD

**Issue by pratiksawant10** [contentful/contentful-export#249]
Usage:
const contentfulExport = require('contentful-export')

Error:
ERROR in ./node_modules/contentful-export/dist/parseOptions.js
Module not found: Error: Can't resolve '../package' in '/Users/sawantp/applicant-portal/applicant-portal-api/node_modules/contentful-export/dist'
 @ ./node_modules/contentful-export/dist/parseOptions.js 19:15-36
 @ ./node_modules/contentful-export/dist/index.js
 @ ./src/functions/endpoints/contentful-backup/create/index.ts

WARNING in ./node_modules/contentful-export/dist/parseOptions.js 44:37-94
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/contentful-export/dist/index.js

WARNING in ./node_modules/any-observable/register.js 15:14-37
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/any-observable/index.js
 @ ./node_modules/@samverschueren/stream-to-observable/index.js
 @ ./node_modules/listr/lib/task.js
 @ ./node_modules/listr/index.js
 @ ./node_modules/contentful-export/dist/index.js

How can I fix this error as it's not allowing me to deploy my stack using aws sam

**Comment by marcolink** [comment]
Hi @pratiksawant10 👋 

As this issue has been unanswered for a while, I'm closing it now. 
If you're still experiencing this issue with the latest build, feel free to open the issue again.

**Comment by pratiksawant10** [comment]
Thanks Marco
