### ISSUE TITLE
Can't export without drafts

### ISSUE THREAD

**Issue by szimek** [contentful/contentful-export#25]
I've got the following config file:
```json
{
  "spaceId": "xxx",
  "managementToken": "xxx",
  "includeDrafts": false,
  "downloadAssets": false
}
```
When I run `contentful-export --config export-config.json`, I'm getting the following error: `Missing required argument: preview-token`.

When I add it, so that my config file looks like:
```json
{
  "spaceId": "xxx",
  "managementToken": "xxx",
  "previewToken": "xxx",
  "includeDrafts": false,
  "downloadAssets": false
}
```
I'm getting `ERR! Please make sure to specify --include-drafts to be able to get drafts` error.

**Comment by Khaledgarbaya** [comment]
@szimek, Sorry for that I am fixing that soon, please follow this PR https://github.com/contentful/contentful-export/pull/24

**Comment by benben** [comment]
Ran it that too, neither `--include-drafts=false`, `--include-drafts false` or omitting the option works

**Comment by Khaledgarbaya** [comment]
this issue is resolved in the new version
