### ISSUE TITLE
Process exits with status 0 on error; should be non-zero

### ISSUE THREAD

**Issue by apaatsio** [contentful/contentful-export#27]
The contentful-export script exits with status 0 even when there are errors. This is problematic if you are running this script via another script or in a CI tool like Jenkins. 

It should return a non-zero error code on error.

I noticed this when I experienced the error described in #26

**Comment by Khaledgarbaya** [comment]
Hi @apaatsio,
Sorry for the late response I will tackle this asap, PR are welcome also :) if it is urgent for you

Best,
Khaled

**Comment by apaatsio** [comment]
Not urgent :)

**Comment by axe312ger** [comment]
This is fixed in the latest major. It exits with non-zero exit code when errors occurred.
