### ISSUE TITLE
opts and errorLogFile are undefined in runContentfulExport 

### ISSUE THREAD

**Issue by AndrewBresee** [contentful/contentful-export#35]
When runContentfulExport is called in bin, `setTimeout(function () {
  runContentfulExport(usageParams)...` it is called with only usageParams. 

`let {opts, errorLogFile} = usageParams` is incorrectly set. ES6 interprets it as `let opts = usageParams.opts, let errorLogFile = usageParams.errorLogFile`

opts being undefined,  maxAllowedLimit and includeDrafts can not be set. This issue was brought up [here](https://github.com/contentful/contentful-export/issues/32). 

Additionally, errorLogFile being undefined is reflected in the issue [here](https://github.com/contentful/contentful-export/issues/27).  

Working PR out as a patch [here](https://github.com/contentful/contentful-export/pull/34).

**Comment by Khaledgarbaya** [comment]
Hi @AndrewBresee, I didn't get your point the `opts` and `errorLogFile ` are set [here](https://github.com/contentful/contentful-export/blob/master/lib/usageParams.js#L67-L70)

**Comment by AndrewBresee** [comment]
ah, my mistake. I was wrong about where they are set. 

However, if you were to console log opts inside of runContentfulExport, it is undefined.

**Comment by Khaledgarbaya** [comment]
@AndrewBresee Are you using content-export as a node module ? or as a cli ?

**Comment by AndrewBresee** [comment]
@Khaledgarbaya As a node module. I can hack a solution by going into the content-export module and putting a static number in for maxAllowedLimit in the run-contentful-exports.js file. Either that or make the changes to the code that I submitted a [PR for here](https://github.com/contentful/contentful-export/pull/34).

**Comment by Khaledgarbaya** [comment]
Why not just passing `{opts:{'maxAllowedItems': 100 ....}, errorLogFile: 'filename'}`

**Comment by Khaledgarbaya** [comment]
```js
var spaceExport = require('contentful-export')
var opetions = {opts:{'maxAllowedItems': 100 ....}, errorLogFile: 'filename'}
spaceExport(options)
.then((output) => {
  console.log('space data', output)
})
.catch((err) => {
  console.log('oh no! errors occurred!', err)
})
```

**Comment by AndrewBresee** [comment]
This should work! But it was not how the options were specified in the README.

**Comment by axe312ger** [comment]
Good point, I fixed the documentation, will be in master soon :)
