### ISSUE TITLE
Any way to skip Fetching assets at all?

### ISSUE THREAD

**Issue by nicolaaretini** [contentful/contentful-export#374]
I've noticed that calling the tool with following options

`
{ 
 spaceId,
 environmentId,
 managementToken,
 queryEntries: [
    `content_type=myContentTypeId`,
 ],
 contentOnly: true,
 contentFile: filePath,
 downloadAssets: false,
 yes: true
}
`

even though "myContentTypeId"  has no assets references and I've set 
downloadAssets: false,

I see while running a step (not skipped) of

 ✔ Fetching assets data

which is time consuming.

Because it's actually fetching all the assets (references I guess)  on my  environmentId / managementToken

And what I wish is to get only contents no assets.

**Comment by nicolaaretini** [comment]
Found this hack 

 queryAssets: [
            'sys.id=xxx'
        ],

so no waste in looking for fetching assets.

Anyhow a

`skipAssets:true`

parameter would solve this issue IMHO

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
