### ISSUE TITLE
Any plans for an import tool? 

### ISSUE THREAD

**Issue by eisenbergrobin** [contentful/contentful-export#4]
This tool allow me to export Contentful spaces and keep backups available.

Do you have any plans to make the same tool in reverse, to handle importing of a Space from a JSON dump generated using `contentful-export`?

**Comment by Khaledgarbaya** [comment]
Hi @eisenbergrobin,

Yes We are working on a `contentful-export` and it should be out soon.

Best,
Khaled

**Comment by eisenbergrobin** [comment]
:+1: Great, looking forward to it. 

Thanks
