### ISSUE TITLE
usage as a library doesn't work as expected

### ISSUE THREAD

**Issue by cachrisman** [contentful/contentful-export#43]
using the example given in the Readme:

```
var spaceExport = require('contentful-export')
var options = {
  maxAllowedItems: 100,
  errorLogFile: 'filename',
  ...
}
spaceExport(options)
.then((output) => {
  console.log('space data', output)
})
.catch((err) => {
  console.log('oh no! errors occurred!', err)
})
```

only returns `space data undefined`.

It seems the tool should know when it is being run as a library and directly return the data rather than write it to a json file.

**Comment by Khaledgarbaya** [comment]
Hey @cachrisman @axe312ger will take care of this asap

**Comment by Khaledgarbaya** [comment]
This is now fixed in https://github.com/contentful/contentful-export/pull/44#pullrequestreview-30198890
