### ISSUE TITLE
Include an option to specify filename?

### ISSUE THREAD

**Issue by Pedootz** [contentful/contentful-export#45]
Hi Contentful,

My name is Tom, I'm an engineer at Huge.  I know that our engineers and Contentful have had an ongoing dialogue around this tool (along with the export tool) and that some of the 4.1 changes were the result of the conversation we had a few weeks ago.  I'd find it really useful to be able to specify an output filename as an option, with the fallback being existing behavior.  Would you guys be receptive to that?  I have no problem submitting a PR including this feature if you'd like.

Best,
Tom Peduto (and Huge)

**Comment by Khaledgarbaya** [comment]
Hi @Pedootz,
That's a Great idea and of course, PRs are always welcome.
Best,
Khaled

**Comment by dustinaleksiuk** [comment]
This would be super valuable for me as well. We can adapt to your hard-coded filename, but our scripts will fail if you ever change it. It would be much better to just allow us to specify the filename.

**Comment by axe312ger** [comment]
Added this ticket to the v5 milestone. A PR is very welcome, the v5 is currently developed in the `next` branch

**Comment by dustinaleksiuk** [comment]
@axe312ger - I realize now that I can grab the output from spaceExport in the callback and write that to a file myself, so this might not be as valuable as I thought at the time.

**Comment by axe312ger** [comment]
Would still be great to offer this option also from the CLI. It is low priority anyways 🙈

**Comment by Khaledgarbaya** [comment]
this is now possible using `--content-file`
