### ISSUE TITLE
export specific content types or models

### ISSUE THREAD

**Issue by matt-lavinia** [contentful/contentful-export#47]
A nice addition would be the ability to define a comma-separated list of models / entries to export from a specific space.

i.e. ) 
I have a space that has models X, Y, & Z. 
I want to get all entries of type Y & Z only via the export utility.
I then want to import only entries of type Z to a new space on a daily basis.

A param like:
entry-content-types=Y,Z

**Comment by axe312ger** [comment]
Yeah sweet idea Matt, we will add it to our feature list :)

**Comment by dustinWeaver** [comment]
I second this idea.  Would help with large content models where only few types have changed.

**Comment by ahmettaha** [comment]
+1

**Comment by timrobertson100** [comment]
+1

**Comment by axe312ger** [comment]
Just want to mention we have this on the radar and it will be implemented asap :)

**Comment by timrobertson100** [comment]
It would be nice (although I imagine not totally easy) if it could also bring only the assets associated with the entries being exported.

**Comment by axe312ger** [comment]
Hmm, this adds extra complexity but would make sense. I'll keep it in mind :)

**Comment by axe312ger** [comment]
Added this ticket to the v5 milestone. A PR is very welcome, the v5 is currently developed in the next branch

**Comment by iddan** [comment]
If I may add for this: We need the ability to include drafts only for specific content types

**Comment by axe312ger** [comment]
This is totally possible with the new `--query-entries` feature of the new versions. You just have to do multiple exports. One for the content types including drafts, another for the ones without.

Then import twice

**Comment by axe312ger** [comment]
As mentioned, this is now possible via `--query-entries`. Closing this issue :)

**Comment by matt-lavinia** [comment]
Great! Thanks for handling this.
