### ISSUE TITLE
RangeError: Invalid string length error

### ISSUE THREAD

**Issue by longh957** [contentful/contentful-export#50]
Get the following error when I run the tool, in my config i have skipContentModel set to true, and maxAllowedLimit at 100. 

```
ERR! export RangeError: Invalid string length
ERR! export     at JSON.stringify (<anonymous>)
ERR! export     at stringify (/usr/local/lib/node_modules/contentful-export/node_modules/json-stringify-safe/stringify.js:5:15)
ERR! export     at /usr/local/lib/node_modules/contentful-export/dist/index.js:148:80
ERR! export  Failed with
ERR! export  RangeError: Invalid string length
ERR! export     at JSON.stringify (<anonymous>)
ERR! export     at stringify (/usr/local/lib/node_modules/contentful-export/node_modules/json-stringify-safe/stringify.js:5:15)
ERR! export     at /usr/local/lib/node_modules/contentful-export/dist/index.js:148:80
```

**Comment by Khaledgarbaya** [comment]
Hi @longh957,
This error is coming from V8 which should actually be `OutOfMemory` due the to the size of the exported data that you're trying to stringify.
I will take a look into this asap, and maybe try to use streams when exporting data

**Comment by axe312ger** [comment]
Hey @longh957,

I will try to replicate, can you maybe share some information how big the Space is, you are trying to export? Number of entries, assets etc?

Meanwhile I will create a new branch, which will use streams to write the JSON file, hopefully getting rid of the memory error then.

Cheers,
Benedikt

**Comment by axe312ger** [comment]
@longh957 here we go, I think this could help you. Could you check if the the branch of this PR fixes your memory issue?

https://github.com/contentful/contentful-export/pull/59

**Comment by longh957** [comment]
Thanks @axe312ger, I will check it out and let you know how it goes. For your previous question, the space we are using has about 60k entries, 200k assets, and about 44 content types.

**Comment by axe312ger** [comment]
@longh957 the newest version should be able to export huge data sets. Feel free to upgrade and please tell me if it worked out for you :)
