### ISSUE TITLE
Rate limit hit on run

### ISSUE THREAD

**Issue by jonocairns** [contentful/contentful-export#51]
Is there any way to internally drip feed the requests so they won't hit the management API rate limit? 10 requests per second is hit almost instantly when I run the export.

https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/api-rate-limits

**Comment by Khaledgarbaya** [comment]
Hi @jonocairns,
The tool is already taking care of the rate limit for you automatically and resends the request.
So no need to configure that client side.
Best,
Khaled

**Comment by jonocairns** [comment]
@Khaledgarbaya thanks for the reply 👍 

Is it hitting the limit then throttling or proactively doing it? Is there any chance of losing service while the limit resets, even if for a second? Is there any chance of hitting the hourly cap then completely losing service until the hour is up? Do you know if the rate limits are endpoint specific (as in, if you hit the rate limit in api you can still access cdn)?

Cheers,
Jono

**Comment by Khaledgarbaya** [comment]
Hi @jonocairns,
> Is it hitting the limit then throttling or proactively doing it? 
Yes, the tool hit the rate limit and gets a rate limit header telling it when it safe to send the request again. the tool takes that value and adds a jitter to it.

>Is there any chance of losing service while the limit resets, even if for a second? 

>Is there any chance of hitting the hourly cap then completely losing service until the hour is up?
With the tool, you should not hit the hourly

>Do you know if the rate limits are endpoint specific (as in, if you hit the rate limit in api you can still access cdn)?
The rate limit is per organization so anyone using any data from that org will be affected. It is recommended to use the content delivery API when pulling content for your website because it is read only and rate limit is higher.

**Comment by jonocairns** [comment]
Hey @Khaledgarbaya,

I'll add a bit of info for what I mean by service. Currently the rate limit for the API is 10 requests per second or 36000 per hour.

> For requests that do hit the CMA, there is a rate limit of 36000 requests per hour and 10 requests per second. Higher rate limits might apply for enterprise clients.

We currently use the cdn for the majority of operations. This is required to be up 24/7 to serve content to a site. I'm worried that hitting the rate limit cap on the API for this backup/extract will cause requests to get denied with the retry header on the CDN.

Let's say for example you fire 10 requests and the rate limit is hit at 300ms. This means that ANY request to the API OR CDN will be denied (rather the rate limit header is returned but is effectively a deny with a 'you can call in X ms / seconds) for the next 700ms. The same goes with the hourly rate limit. This would mean that if you want to run this extract it would have to be done during a maintenance period to ensure no other (cdn or content related) requests are hit with the rate limit and thus either add extra load or deny service. 

If you drip fed the requests, taking in to account the current rate limits for the API, you would not need to a) deny service till the rate limit has been reset and b) take care or reduce complexity for the retry logic. This would make the request strategy proactive rather than reactive. Clients could then use this tool to backup or extract more frequently.

**Comment by Khaledgarbaya** [comment]
Hi @jonocairns you don't have to worry about that the Content Delivery API rate limit is much higher and is not affected by the CMA.

**Comment by jonocairns** [comment]
Great, thanks for that @Khaledgarbaya

**Comment by floelhoeffel** [comment]
Rate limit on CDA and CMA are separately calculated. Furthermore CDA has
caching on CDN edge hence all requests against the cache do not count
towards CDA rate limits at all.

CDA rate limit usually never gets into effect with a sane caching strategy.
E.g. don't append a timestamp to requests or push updates to a space on a
very high rate for a long time.

Am 25.04.2017 10:56 nachm. schrieb "Jono Cairns" <notifications@github.com>:
