### ISSUE TITLE
Export promise does not include content

### ISSUE THREAD

**Issue by matt-tingen** [contentful/contentful-export#53]
This was observed on 4.4.0 and 4.5.0.
It seems to be a regression of #43.

Running this:
```javascript
const exportSpace = require('contentful-export');

exportSpace({
  managementToken: '...',
  spaceId: '...',
  saveFile: false
}).then(content => {
  console.log('content:', content);
});
```
yields output `content: undefined`.

Expected behavior is for `content` to be an object containing the space's content.

**Comment by Khaledgarbaya** [comment]
Hi @matt-tingen let take a look at this get back to you asap
