### ISSUE TITLE
getFullSourceSpace.then is not a function

### ISSUE THREAD

**Issue by matt-tingen** [contentful/contentful-export#55]
This was observed on 4.5.1.

It looks like the API of `getFullSourceSpace` changed to no longer return a promise in the [recent version bump](https://github.com/contentful/contentful-export/commit/0bc09f578af460599ae4b074ceecaccb4f772bfd) of `contentful-batch-lib`.
Let me know if you want me to re-file the issue on `contentful-batch-lib`, instead.

Running this:
```javascript
const exportSpace = require('contentful-export');

exportSpace({
  managementToken: '...',
  spaceId: '...',
  saveFile: false
}).then(content => {
  console.log('content:', content);
});
```
yields output 
```
 ✔ Initialize clients
 ✖ Fetching data from space
   → (0 , _getFullSourceSpace2.default)(...).then is not a function
   Download assets
   Writing data to file
```

Expected behavior is for the export to complete without error.

**Comment by Khaledgarbaya** [comment]
Hy @matt-tingen ,
Sorry about that @axe312ger will take a look asap and fix that

**Comment by Khaledgarbaya** [comment]
This is now fixed in https://github.com/contentful/contentful-export/commit/270ce478c29091855686c1bbb91c2e1368a104f2
