### ISSUE TITLE
Export all assets of type image and size greater than 600kb

### ISSUE THREAD

**Issue by Vykuntarao-n** [contentful/contentful-export#644]
Could you help you me in downloading all the assets of type only images and the size is greater than 600kb ? 
I have tried this not working !! 
contentOnly : true, 

  queryEntries: [

    //Skip all entries

    'sys.id=1'

    //'content_type=<content_type_id>',

    //'sys.id=<entry_id>'

  ],

  queryAssets : [

    'fields.file.contentType=image/jpeg',

    ‘fields.file.contentType=image/png',

    ‘fields.file.contentType=image/svg+xml'

  ], 

  downloadAssets: false

**Comment by marcolink** [comment]
Hi @Vykuntarao-n  

based on the asset entity shape defined [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/assets), you could try  [`'fields.file.details.size[gt]=600000'`]

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
