### ISSUE TITLE
Different result on export vs CDN API

### ISSUE THREAD

**Issue by tomasdev** [contentful/contentful-export#70]
I have 2 entries in my space, with different content types.
```js
spaceExport({
    managementToken,
    spaceId: FROM_SPACE_ID,
    saveFile: false,
    skipWebhooks: true,
    skipRoles: true,
    skipContentModel: false
})
```

and `https://cdn.contentful.com/spaces/FROM_SPACE_ID/entries?select=fields&locale=*` return different things. I'll paste the keys of the objects only:

NODEJS:
```
// Entry #1 fields keys
[ 'translations',
  'dislcaimers',
  'name',
  'locale',
  'globalContent',
  'navigation',
  'transitions',
  'disclaimers' ]
// Entry #2 fields keys
[ 'name', 'translations' ]
```

CDN API:
```
// Entry #1 fields keys
[ 'name',
  'locale',
  'globalContent',
  'navigation',
  'transitions',
  'disclaimers'
]
// Entry #2 fields keys
[ 'name', 'translations' ]
```

Also note how via NodeJS I'm getting a `dislcaimers` (typo) field on an entry that API doesn't have it at all. And I'm using include drafts false (default value)

**Comment by axe312ger** [comment]
Hey Tomas,

it looks like you disabled the `dislcaimers` field for the response.

This option is only taken into account in the CDA/CDN. The export tool uses the management API which always includes all fields.

Hope that helps,
Benedikt
