### ISSUE TITLE
NPM Error Path - .staging\trier-49b97969

### ISSUE THREAD

**Issue by steveninmanCubs** [contentful/contentful-export#71]
Hi,

I'm attempting to leverage this code to spin up some test environments in Contentful.  I have reinstalled all the way back down to Node locally and still running into this error on installation.  Any thoughts?  I swapped out my username below

npm ERR! path C:\Users\<username>\AppData\Roaming\npm\node_modules\.staging\trier-49
b97969\h

Let me know if you want the detailed log

**Comment by Khaledgarbaya** [comment]
Hi @steveninmanCubs this looks like an npm issue, it looks like `npm install` was running out of memory. Can you try to clear npm caches or increase the swap file size?

**Comment by steveninmanCubs** [comment]
The latest version of NPM self heals on any cache issues.  It's always possible to run it with --force, but I thought that wouldn't be an issue.  I ran a cache verify and seems ok:
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 1027 (19929206 bytes)
Index entries: 1740
Finished in 46.24s

Will poke around the swap file size next.

**Comment by steveninmanCubs** [comment]
Looks like I have 8 GB of swap allocated on my machine.

Do you recommend more, that seems like quite a bit.

**Comment by Khaledgarbaya** [comment]
Hmm this is weird, 8GB should be enough I guess and the package is not that big to require all of that. Can you try installing the package with yarn? Which npm and node versions do you use?

**Comment by steveninmanCubs** [comment]
Node v6.11.2
NPM 5.3.0

Here is the bottom of a verbose logging install

npm http fetch GET 200 https://registry.npmjs.org/spdx-license-ids 7ms (from cac
he)
npm verb correctMkdir C:\Users\sinman\AppData\Roaming\npm-cache\_locks correctMk
dir not in flight; initializing
npm verb lock using C:\Users\sinman\AppData\Roaming\npm-cache\_locks\staging-bb2
a88b8edec59df.lock for C:\Users\sinman\AppData\Roaming\npm\node_modules\.staging

http fetch GET 200 https://registry.npmjs.org/trier/-/trier-0.3.6.tgz 627ms (fro
m cache)
http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-5.4.3.tgz 66ms (from c
ache)
npm verb unlock done using C:\Users\sinman\AppData\Roaming\npm-cache\_locks\stag
ing-bb2a88b8edec59df.lock for C:\Users\sinman\AppData\Roaming\npm\node_modules\.
staging
npm verb type OperationalError
npm verb stack Error: ENOENT: no such file or directory, open 'C:\Users\sinman\A
ppData\Roaming\npm\node_modules\.staging\trier-49b97969\h

**Comment by Khaledgarbaya** [comment]
Can you create the folder `C:\Users\sinman\A
ppData\Roaming\npm\node_modules.staging\trier-49b97969\h` and try again or try to install the package using yarn

**Comment by steveninmanCubs** [comment]
Yeah, I tried manually creating that folder before reaching out to you and still had same issue.

Installing yarn now.  Assuming once I get this in place should run: yarn global add contentful-export

**Comment by steveninmanCubs** [comment]
C:\development\contentful-export>yarn global add contentful-export
yarn global v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/trier/-/trier-
0.3.6.tgz: ENOENT: no such file or directory, open 'C:\\Users\\sinman\\AppData\\
Local\\Yarn\\cache\\v1\\npm-trier-0.3.6-61a80f44f8d7a24704f7628ada70c2c79325667d
info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\Users\\sinman\\AppData\\Local\\Yarn\\config\\global\\yarn-error.
log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this c
ommand.

**Comment by Khaledgarbaya** [comment]
Hi @steveninmanCubs I will try to get a windows machine and test this, I just tried installing the package and it was working fine.

**Comment by steveninmanCubs** [comment]
We have attempted it on both Windows 7 and Windows 10 OS and same issue on both.

**Comment by Khaledgarbaya** [comment]
Hi @steveninmanCubs I just switched to a windows machine and I'm having the same issue. I will continue investigating on my side

**Comment by steveninmanCubs** [comment]
Thanks much, appreciate it!  We ran into it with contentful-cli too, but contentful-import works fine.

**Comment by Khaledgarbaya** [comment]
Hi @steveninmanCubs so the issue is in the version 4.7 and up, you can for now do npm install -g contentful-export@4.6 until we find the corrupted file and make a new release.
Sorry for the inconvenience

Best,
Khaled

**Comment by steveninmanCubs** [comment]
Awesome, thanks for the quick reply, will do this now and continue on.

**Comment by Khaledgarbaya** [comment]
Hi @steveninmanCubs I identified the corrupted version, it was due to a new dependency we had.
I reported the problem to the dependency maintainer and he will try to release a fix asap
Best,
Khaled

**Comment by steveninmanCubs** [comment]
That makes sense as trying to install that library by itself has the same error.

**Comment by axe312ger** [comment]
This is fixed and released :)
