### ISSUE TITLE
Query (on `next` branch) results in 400 error

### ISSUE THREAD

**Issue by maria-pacana-ck** [contentful/contentful-export#75]
I tried out the new `--query` functionality on the `next` branch. I ran `./bin/contentful-export --config config.json --query content_type=[contentType]` and got an `InvalidQuery` error.

The code is passing the query parameters (`content_type=[contentType]`) to `getFullSourceSpace`. This `content_type` query parameter works with Entries, but not with Assets, which don't have a ContentType. `getFullSourceSpace` is passing the query parameter to the GET for Assets, which is resulting in the `InvalidQuery` error. The GET for Entries works just fine.

It seems that you'll have to filter out the `content_type` query param when setting up the query for Assets.

We need the `--query` flag to work so that we can filter the import of entries by ContentType.

@Khaledgarbaya

**Comment by Khaledgarbaya** [comment]
HI @maria-pacana-ck 
can you try `--query 'content_type=contentType'` note the quotes

**Comment by maria-pacana-ck** [comment]
@Khaledgarbaya  I tried with the quotes but it still doesn't work. It *does* work when I add a filter in `pagedGet` in `get-full-source-space` (over in `contentful-batch-libs`). Inside `pagedGet`, I deleted `content_type` from `query` when the method was not `getEntries`. Then I did another `npm run build` and reran the command, and it worked. I think you might have to update `contentful-batch-libs` and do something similar. You are passing the `content_type` in the query to both the `getEntries` task and the `getEntries` task.

**Comment by maria-pacana-ck** [comment]
Look at this error log file. It specifically references a 400 on the `/assets` URL.

`[
  {
    "ts": "2017-11-29T19:00:02.541Z",
    "level": "error",
    "error": {
      "name": "InvalidQuery",
      "data": {
        "status": 400,
        "statusText": "Bad Request",
        "message": "The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.",
        "details": {
          "errors": [
            {
              "name": "unknown",
              "path": [
                "content_type"
              ],
              "details": "The path \"content_type\" is not recognized"
            }
          ]
        },
        "request": {
          "url": "https://api.contentful.com:443/spaces/mySpace/assets",
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/vnd.contentful.management.v1+json",
            "X-Contentful-User-Agent": "app contentful.export/5.0.0; sdk contentful-management.js/4.1.2; platform node.js/6.11.4; os macOS/16.7.0;",
            "Authorization": "Bearer ...952fb",
            "user-agent": "node.js/v6.11.4",
            "Accept-Encoding": "gzip"
          },
          "method": "get"
        },
        "requestId": "69f4a8cbb1551db0b48109637f10c52e"
      }
    }
  }
]`

**Comment by Khaledgarbaya** [comment]
ah @maria-pacana-ck good catch,
I will take a look at that tomorrow.

**Comment by Khaledgarbaya** [comment]
Hi @maria-pacana-ck,
the issue should be fixed now, the param`--query` is now split between `--query-entries` and `--query-assets`.
Your command should be 
```
./bin/contentful-export --config config.json --query-entries content_type=[contentType]
```
