### ISSUE TITLE
Attempting to export locales

### ISSUE THREAD

**Issue by frederickbrock** [contentful/contentful-export#79]
I am currently attempting to export content from a space. When the tool attempts to export locales I receive a 404. I am not sure the tool has a defect, but I am trying to determine which piece of content has an invalid link or if I am not exporting correctly. 

The error: 
  {
    "ts": "2018-01-03T00:24:18.286Z",
    "level": "error",
    "error": {
      "name": "NotFound",
      "data": {
        "status": 404,
        "statusText": "Not Found",
        "message": "The resource could not be found.",
        "details": {
        },
        "request": {
          "url": "https://api.contentful.com:443/spaces/<<REMOVED>>/locales",
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/vnd.contentful.management.v1+json",
            "X-Contentful-User-Agent": "app contentful.export/6.0.1; sdk contentful-management.js/4.1.2; platform node.js/6.9.3; os macOS/16.7.0;",
            "Authorization": "Bearer ...b06a9",
            "user-agent": "node.js/v6.9.3",
            "Accept-Encoding": "gzip"
          },
          "method": "get"
        },
        "requestId": "be777c4a0e4e3cca1b585136eb64d1a7"
      }
    }
  } 

The command line 

contentful-export --config ./wisdompanel-config.json  --save-file true --download-assets true --export-dir ./export_from_breelib

The config file simply has my management token and space id.

**Comment by axe312ger** [comment]
He Fredrick,

Looks like a configuration problem to me.

Did you check twice if your spaceid is correct, you management token is valid and you can access locales on that space?

Best,
Benedikt

**Comment by Khaledgarbaya** [comment]
Hey @frederickbrock ,
Locales are only available if you are an admin. Make sure to have an admin token.
Best,
Khaled

**Comment by axe312ger** [comment]
No feedback for about 1.5 months. Closing this issue, feel free to post here or open a new one if it is still an issue for you.
