### ISSUE TITLE
Documentation for arguments to --query-entries lacking

### ISSUE THREAD

**Issue by aleks-dfds** [contentful/contentful-export#81]
The format for the arguments to --query-entries is not clear, it would be great to read more about it in 
1) README.md
2) content-export --help

Both the json and the commandline versions would be great to describe, otherwise it takes a lot of poking around to figure it out.

**Comment by axe312ger** [comment]
Hey Aleks,

how about https://github.com/contentful/contentful-export/pull/82?

Best,
Benedikt
