### ISSUE TITLE
Error message with failed export + options not working

### ISSUE THREAD

**Issue by christineywang** [contentful/contentful-export#88]
I am trying to export a very large space with over 160,000 entries.

I've noticed two issues during this experience:

 ### Issue 1:

During the export, the tool hangs on these two lines for a particularly long time:
`Fetching content entries data`
`Writing data to file`

Then, the export fails and I get this error message:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

This happens for both myself and other users.

I did some research on this error and I'm guessing this is happening because the space has a large number of entries. It looks like you can set an option to Node to hopefully bypass this issue but I'm not sure how to configure it:
`--max-old-space-size`

Note: This only happens when I am trying to export very large spaces. All other exports work really well. 👍 

<hr>

### Issue 2:

As a workaround, I would like to export the space in chunks.

I used the `--query-entries` option with two different queries (separately):
`'content_type=contentTypeId'`
`'query-entries 'sys.id=<entry-id>'`

So that my end command looks something like this:

```
contentful-export \
  --space-id spaceID \
  --management-token managementToken
  --query-entries 'content_type=contentTypeId'
```

However, these options aren't working for me. When I run the export, the export is still failing even when I am only trying to export one entry.

As a test, I added these options to an export command for a smaller space that is working and the exported `.json` file is still contains all content types, entries, etc.

Am I using the `--query-entries` option incorrectly or is there an issue with the option?

Thanks!

**Comment by Khaledgarbaya** [comment]
Hi @christineywang ,
> issue 1
which version of the export tool is used

> issue 2
which operating system the user is using can you change the single quote to double quote ?

**Comment by christineywang** [comment]
Hi @Khaledgarbaya,

> Issue 1

I am using the latest version of the export tool (just like the user). It was installed using:
`npm install -g contentful-import@next`

> Issue 2

I am using Mac OS v10.13.2.

Using double quotes does not make the `--query-entries` option work.

<hr>

#### Something else I've noticed:


Additionally, I've been testing the export tool from a Node app. The export also fails. I actually don't get an error message but my terminal crashes after hanging on this line:

<img width="450" alt="eport" src="https://user-images.githubusercontent.com/19804181/35695014-103142c6-0738-11e8-81e3-0dd3b9af9009.png">

When I add the `--query-entries` option to my script file, the export doesn't run and I get this error:
`TypeError: options.queryEntries.join is not a function`

I've tried with both single and double quotes.

This is what the line looks like:
`queryEntries: 'content_type=blogPost',`

Thanks!

**Comment by axe312ger** [comment]
For `queryEntries`: This is actually an array, so you need to use `queryEntries: ['content_type=blogPost'],`

For the rest: We need to investigate, exporting such big spaces is sth we do not test every time.

**Comment by christineywang** [comment]
Hmm, I am still having issues with the `--query-entries` option (even when I put the filter in an array).

When I run this tool via a Node app, I don't get any errors but the export file still contains all content types, not just the one I filtered for.

When I run the tool in the terminal, it stops at this line:
`Fetching content entries data`

And I get this error:
`Error: Status: 400 - Bad Request - Message: The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field. - Details: The path "[content_type" is not recognized - Request ID: 88982417a5979a9b4b8d16b200b2eb29`

**Comment by axe312ger** [comment]
Hey Christine,

yeah, it would help a lot if you could split this up into two separate issues. Easier to track and reply.

For the `query-entities` we'd need more details:
* Which node version are you on?
* Which version of contentful-export do you use?
* Which operating system are you using?
* What is the exact command you are executing?

Thanks :)

**Comment by christineywang** [comment]
[Done](https://github.com/contentful/contentful-export/issues/90).

**Comment by MouldiGABSI** [comment]
Hi @Khaledgarbaya  I'm Having the same issues with --query-entries 
Bellow the command i am trying to execute
contentful-export \
  --space-id $spaceID \
  --management-token $management_Token
  --queryEntries:['content_type=StoriesCarouselBlock']

it export all contentType availables in the space

**Comment by axe312ger** [comment]
@MouldiGABSI 
Using `queryEntries: [...]` is only valid if you use contentful-export as a library. For CLI usage please have a look at the readme file (https://github.com/contentful/contentful-export#querying)

➡️ `--query-entries 'condition A' --query-entries 'condition B'`

**Comment by christineywang** [comment]
Hi @axe312ger,

Just curious, why was this issue closed? I am still having issues with exporting large spaces. Thanks!

**Comment by axe312ger** [comment]
Ohh sorry Christine,

understood it as you already created two separate issues. Please clean up the issue description in the first post here to contain one problem only or create a new one for only one problem each.

Otherwise keeping track of the issue is hard and we continue mixing up answers for two separate problems.

Thanks,
Benedikt
