### ISSUE TITLE
npm ERR! 404 Not Found: @contentful/axios@^0.18.0

### ISSUE THREAD

**Issue by Rclayton78** [contentful/contentful-export#91]
I'm getting this NPM error message: **npm ERR! 404 Not Found: @contentful/axios@^0.18.0**
Is this an NPM registry issue?

Wondering if this could be related:
https://github.com/npm/npm/issues/19254

**Comment by axe312ger** [comment]
Jep, has to be either your machine or a bug in npm. We are downloading this dependency daily on multiple machines and our CI and are not experiencing that problem.

You may try to delete your local npm cache and the `node_modules` directory in your project. This might help.

https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache

Best,
Benedikt

**Comment by Rclayton78** [comment]
We found the issue on our end. We were using a proxy I was unaware of and it was cached. 

Thanks for the help!
