### ISSUE TITLE
--query-entries doesn't apply conditions

### ISSUE THREAD

**Issue by MouldiGABSI** [contentful/contentful-export#93]
Hello,
Am having an issue with --query-entries. Am trying to export a specific contentType by using --query-entries 'content_type=my contentType' but it export all contentType available in my space

**Comment by axe312ger** [comment]
Hey Mouldi,

a few questions:

* which version of contentful-export are you using?
* Can you please provide the full command you are running? (Make sure to stripe out your management token)
* Which operating system are you working with?

Thanks,
Benedikt

**Comment by MouldiGABSI** [comment]
Hello, 
Thank you for your response.
I'm using mac os 10.13.2
The commad i'm trying to execute is:

contentful-export \
--space-id $spaceID \
--management-token $management_Token
--query-entries 'content_type=mycontentType'

**Comment by axe312ger** [comment]
This is all correct and working in our tests. I can just assume:

* You are using an older version of export which does not support the pretty new query feature
* Your content type id is wrong
* The `--query-entries` option does not filter content types, it does filter entries. So it might be you expect the content types to be filtered while the feature is filtering your entries. Please check if the entries got filtered based on your query criteria.

If you are sure that these assumptions are wrong, we might need to dig deeper via an support ticket which allows me to have a look at your space and data.

All the best,
Benedikt

**Comment by axe312ger** [comment]
Hey @shikaan,

I guess what you trying to achieve is to get all entries which have values in the `sv` locale. This is not possible in this ways but you might be able to work around like this:


```
contentful-export --space-id SPACE_ID --query-entries 'content_type=my_ct' 'fields.title[exists]=true' 'locale=sv' --management-token TOKEN
```

This checks if the title fields has a swedish value for a specific content type. Note that your results will then be localized to swedish.

Hope that helps,
Benedikt

**Comment by shikaan** [comment]
Hello @axe312ger,
thanks for the quick reply. 
Unfortunately making the call you suggested didn't return the expected result: I have the correct entries (the ones matched by the `content_type` parameter), but the field appears in every locale not only in `sv`

**Comment by axe312ger** [comment]
Ohh sorry, here the yargs syntax tricked me, it should be:

```
contentful-export --space-id SPACE_ID --query-entries 'content_type=my_ct' --query-entries
 'fields.title[exists]=true' --query-entries 'locale=sv' --management-token TOKEN
```

**Comment by a-lehdet** [comment]
I too am having the same problem. I'm attempting to export only the entries of the content type _label_. I'm using version 4.7.8. My NPM version is 5.7.1. on Mac OS X 10.10.5.

`contentful-export --space-id <SPACE-ID> --management-token <TOKEN> --query-entries 'content_type=label'`

**Comment by axe312ger** [comment]
@a-lehdet Your call is correct but that feature was introduced in version 6. Upgrade the tool get this running.

**Comment by a-lehdet** [comment]
For some reason when I updated contentful-export it only upgraded 4.1.1 --> 4.7.8, but when I reinstalled it, everything works as expected. Thanks!
