### ISSUE TITLE
Extra semicolon in types.d.ts causes build error

### ISSUE THREAD

**Issue by mauritz-lovgren** [contentful/contentful-export#961]
Error during typescript build:

`node_modules/contentful-export/types.d.ts:31:2 - error TS1036: Statements are not allowed in ambient contexts.`

Caused by semicolon at end of `export interface Options { ... };`

**Comment by marcolink** [comment]
Hi @mauritz-lovgren 👋 

just released a fix for it!

**Comment by mauritz-lovgren** [comment]
> Hi @mauritz-lovgren 👋
> 
> just released a fix for it!

Fantastic! 🥇 !!
